# Generated by Django 5.2 on 2025-05-07 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_app', '0002_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
